services:
  sut:
    image: ubuntu:22.04
    command: "true"
    depends_on:
      sut-minimal:
        condition: service_completed_successfully
      sut-basic:
        condition: service_completed_successfully

  sut-minimal:
    image: ubuntu:22.04
    command: "true"
    depends_on:
      sut-minimal-1:
        condition: service_completed_successfully

  sut-basic:
    image: ubuntu:22.04
    command: "true"
    depends_on:
      sut-basic-1:
        condition: service_completed_successfully

  sut-small:
    image: ubuntu:22.04
    command: "true"

  sut-medium:
    image: ubuntu:22.04
    command: "true"

  sut-full:
    image: ubuntu:22.04
    command: "true"

  sut-minimal-1:
    image: ${IMAGE_ID}:${VERSION}-minimal
    command: |
      sh -c '
      set -e

      # check if some basic commands work
      tlmgr --version
      pdftex -v
      tex -v
      bibtex -v

      # check if installation works correctly
      latexmk -v && exit 1
      tlmgr install latexmk
      latexmk -v || exit 1

      echo Tests passed!
      '
      
  sut-basic-1:
    image: ${IMAGE_ID}:${VERSION}-basic
    command: |
      sh -c '
      set -ex
      cd /tmp

      echo "=== STEP 1: Verifica ambiente ==="
      which tlmgr
      tlmgr --version
      echo "PATH: $PATH"

      echo "=== STEP 2: Verifica repository corrente ==="
      tlmgr option repository
      
      echo "=== STEP 3: Test connessione al repository ==="
      wget --spider https://mirror.ctan.org/systems/texlive/tlnet/archive/latexmk.tar.xz
      echo "wget exit code: $?"

      echo "=== STEP 4: Aggiorna repository configuration ==="
      tlmgr option repository https://mirror.ctan.org/systems/texlive/tlnet/
      
      echo "=== STEP 5: Prova installazione latexmk ==="
      tlmgr install latexmk --verify-repo=n
      
      echo "=== STEP 6: Test compilazione ==="
      echo "\documentclass[12pt]{article}" > main.tex
      echo "\begin{document}" >> main.tex
      echo "test" >> main.tex
      echo "\end{document}" >> main.tex
      
      latexmk -pdf main.tex
      ls -la main.pdf

      echo "✅ Tutti i test passati!"
      '
