name: Docker

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          docker-compose --file docker-compose.test.yml build
          docker-compose --file docker-compose.test.yml run sut

  push:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - name: Prepare configuration
        run: |
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "main" ] && VERSION=latest

          GH_IMAGE_ID=ghcr.io/${{ github.actor }}/latex

          echo VERSION=$VERSION
          echo "version=${VERSION}" >> $GITHUB_ENV

          echo GH_IMAGE_ID=$GH_IMAGE_ID
          echo "github_image_id=${GH_IMAGE_ID}" >> $GITHUB_ENV

      - name: Build minimal
        run: |
          make minimal
          docker tag kjarosh/latex:latest-minimal kjarosh/latex:${{ env.version }}-minimal
          docker tag kjarosh/latex:latest-minimal ghcr.io/kjarosh/latex:${{ env.version }}-minimal

      - name: Build basic
        run: |
          make basic
          docker tag kjarosh/latex:latest-basic kjarosh/latex:${{ env.version }}-basic
          docker tag kjarosh/latex:latest-basic ghcr.io/kjarosh/latex:${{ env.version }}-basic

      - name: Build small
        run: |
          make small
          docker tag kjarosh/latex:latest-small kjarosh/latex:${{ env.version }}-small
          docker tag kjarosh/latex:latest-small ghcr.io/kjarosh/latex:${{ env.version }}-small

      - name: Build medium
        run: |
          make medium
          docker tag kjarosh/latex:latest-medium kjarosh/latex:${{ env.version }}-medium
          docker tag kjarosh/latex:latest-medium ghcr.io/kjarosh/latex:${{ env.version }}-medium
          docker tag kjarosh/latex:latest-medium kjarosh/latex:${{ env.version }}
          docker tag kjarosh/latex:latest-medium ghcr.io/kjarosh/latex:${{ env.version }}

      - name: Build full
        run: |
          make full
          docker tag kjarosh/latex:latest-full kjarosh/latex:${{ env.version }}-full
          docker tag kjarosh/latex:latest-full ghcr.io/kjarosh/latex:${{ env.version }}-full

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push images
        run: |
          docker push kjarosh/latex:${{ env.version }}-full
          docker push kjarosh/latex:${{ env.version }}-small
          docker push kjarosh/latex:${{ env.version }}-basic
          docker push kjarosh/latex:${{ env.version }}-minimal
          docker push kjarosh/latex:${{ env.version }}-medium
          docker push kjarosh/latex:${{ env.version }}
          docker push ghcr.io/kjarosh/latex:${{ env.version }}-full
          docker push ghcr.io/kjarosh/latex:${{ env.version }}-small
          docker push ghcr.io/kjarosh/latex:${{ env.version }}-basic
          docker push ghcr.io/kjarosh/latex:${{ env.version }}-minimal
          docker push ghcr.io/kjarosh/latex:${{ env.version }}-medium
          docker push ghcr.io/kjarosh/latex:${{ env.version }}

  update-description:
    needs: push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Update repo description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: kjarosh/latex
